suse-edge/edge-image-builder

pkg/config/image.go
It worked without this because of the conventions of how YAML is parsed by default, but for completeness I'm adding the flag.
=> added explicit yaml tag for image

Dockerfile, pkg/build/build.go, pkg/build/iso.go, pkg/build/iso_test.go, pkg/build/raw.go, pkg/build/raw_test.go, pkg/build/scripts/modify-raw-image.sh, pkg/config/image.go
Uses libguestfs inside of the container. This implementation currently only works on x86 (fails on aarch64) due to differences in the containers. Due to package availability, the EIB container image was changed to Leap. We may be able to readdress this in the future.
=> Raw image modification implementation

.gitignore, .idea/.gitignore, pkg/build/build.go, pkg/build/rpm.go, pkg/build/rpm_test.go
Currently working on getting elemental registration through combustion working in eib. So far, I've been able to get it work with some few hacks (which are omitted from here, along with the Elemental specific stuff as it is not complete). To get there though, I needed to be able to add the RPMs to the image, so I built the handling for that as well as the tests. I’m not sure if this is how you guys would have gone about it, so I’ve made this PR a draft for now
=> added handling for adding rpms to an image as well as the relevant tests

pkg/build/build.go, pkg/build/build_test.go, pkg/build/message.go, pkg/build/raw.go, pkg/build/raw_test.go
As part of this, I refactored the writeBuildDirFile and writeCombustionDirFile methods to return the full name of the file written. They are meant to be utility functions to prevent the caller from having to manually assemble the full paths to common locations, and it makes sense that these calls would also tell the user what the filename ended up being.
closes #29
=> Fixed issue where the modify script for raw images could not be executed

pkg/build/grub.go, pkg/build/grub_test.go, pkg/build/raw.go, pkg/build/raw_test.go, pkg/build/scripts/grub/guestfish-snippet.tpl, pkg/build/scripts/modify-raw-image.sh.tpl, pkg/config/image.go, pkg/config/image_test.go, pkg/config/testdata/valid_example.yaml
We may have to revisit the actual sed commands once we more thoroughly test this, but this does currently work. Hopefully, those sorts of changes should have a minimal footprint and the rest of the structure used in this PR will remain.
We also may have to revisit how we get things into the modify-raw-image.sh template. That'll be affected by both the need to do this for manipulating the squashed raw image inside of an ISO (that's coming up soon on my todo list) as well as a refactoring if we end up jamming a lot into the guestfish command. But for now, this should be a reasonable start to build on and readdress when we have a clearer picture of what everything looks like.
=> Working implementation of GRUB configuration for raw images

pkg/build/build.go, pkg/build/build_test.go, pkg/build/grub.go, pkg/build/message.go, pkg/build/raw.go, pkg/build/raw_test.go, pkg/build/rpm.go, pkg/build/rpm_test.go, pkg/build/scripts.go, pkg/build/scripts_test.go, pkg/build/users.go, pkg/build/users_test.go, pkg/fileio/file_io.go, pkg/fileio/file_io_test.go, pkg/template/template.go, pkg/template/template_test.go
- Initially aimed to add perms to `fileio` functions in order to drop unnecessary and prone to missing additional `Chmod()` calls
- Led to splitting up the initial `WriteFile` implementation to two separate parts `WriteFile` for non-templated files and `WriteTemplate` for templated ones
- `WriteFile` at that point was just a wrapper around `os.WriteFile` and `WriteTemplate` was doing too many things for a single function
- As a result, the `template` package was extracted and reused where applicable and `WriteFile` was removed. This decouples templating from IO ops and further simplifies combustion components structure and testing
=> Split templating from file IO operations

docs/building-images.md
In the existing documentation we state that there are "no restrictions on the naming" of the input image that is specified in the EIB configuration, therefore the following should _always_ work just fine:
```
rdo@woden:~/work/eib% cat eib-config-iso.yaml 
apiVersion: 1.0
image:
imageType: iso
baseImage: slemicro5.5.iso
outputImageName: eibimage.iso
```
However, if you're utilising `nmc` to do static networking configuration, the EIB run fails with an error suggesting that it could not determine the architecture of the image:
```
2023-12-19T16:08:03.649Z	DEBUG	build/iso.go:55	ISO log file created: /eib/_build/iso-build-Dec19_16-08-03.log
rdo@woden:/tmp/eib/_build% cat eib-build-Dec19_15-58-09.log
2023-12-19T15:58:09.311Z	INFO	combustion/network.go:51	Configuring network component... …
```
=> Docs: Ensure that all image filenames contain the architecture

pkg/combustion/templates/add-users.sh.tpl
- Closes https://github.com/suse-edge/edge-image-builder/issues/66
- Using the [TestConfigureUsers](https://github.com/suse-edge/edge-image-builder/blob/main/pkg/combustion/users_test.go#L14) test to showcase the difference
**Before:**
```
#!/bin/bash
set -euo pipefail
mount /home
useradd -m alpha
echo 'alpha:alpha123' | chpasswd -e
mkdir -pm700 /home/alpha/.ssh/
echo 'alphakey' >> /home/alpha/.ssh/authorized_keys
chown -R alpha /home/alpha/.ssh
useradd -m beta
echo 'beta:beta123' | chpasswd -e
useradd -m gamma
mkdir -pm700 /home/gamma/.ssh/
echo 'gammakey' >> /home/gamma/.ssh/authorized_keys
chown -R gamma /home/gamma/.ssh
echo 'root:root123' | chpasswd -e
mkdir -pm700 /root/.ssh/
echo 'rootkey' >> /root/.ssh/authorized_keys
```
**After:**
```
#!/bin/bash
set -euo pipefail
mount /home …
```
=> Fix whitespaces in users template

pkg/combustion/templates/12-suma-register.sh.tpl
In the previous version, at bootup the service was restarted, which wouldn't work properly during combustion, it simply needed to be enabled.
=> SUMA: venv-salt-minion needs to be enabled not restarted

pkg/build/raw.go, pkg/build/raw_test.go, pkg/build/templates/modify-raw-image.sh.tpl
- Stores the output of guestfish modifications for raw images in a `raw-build.log` file under the build directory
=> Log raw build output

cmd/eib/main.go, docs/building-images.md, pkg/build/build.go, pkg/combustion/network.go, pkg/combustion/network_test.go, pkg/image/context.go, pkg/image/definition.go, pkg/image/definition_test.go, pkg/image/testdata/full-valid-example.yaml, pkg/image/validation.go, pkg/image/validation_test.go, pkg/network/configurator_installer.go, pkg/network/configurator_installer_test.go
- Adds a new `arch` field to the image definition file
- Includes validation for the new field
- Drops image name requirements for network component
- Sets up a graceful recovery from runtime errors / panics
=> Add arch to definition

pkg/fileio/file_io.go, pkg/fileio/file_io_test.go
Introduce the copy file content by byte chunks logic introduced in #64 in a separate PR in order to reduce complexity of #64
=> Introduce copy file content by byte chunks logic

pkg/image/definition.go, pkg/image/definition_test.go, pkg/image/testdata/full-valid-example.yaml, pkg/image/validation.go, pkg/image/validation_test.go
- Introduces kubernetes definition and validation
- Possible configurations are kept to a minimum
- Follow ups might introduce more options e.g. SELinux
=> Add kubernetes definition

Dockerfile, pkg/build/iso.go, pkg/build/iso_test.go, pkg/build/templates/extract-iso.sh.tpl, pkg/build/templates/rebuild-iso.sh.tpl
This has no net new functionality, but lays the groundwork to refactor the raw image modifications to be done for ISOs as well.
I do want to (eventually) add a test ISO (obviously a custom built one and not a GB-sized one) to actually run the scripts against, but for now the tests prove that the correct values are passed into the templates.
=> Added logic to unsquash/resquash the raw image inside of the ISO

pkg/image/definition.go, pkg/image/definition_test.go, pkg/image/testdata/full-valid-example.yaml, pkg/image/validation.go, pkg/image/validation_test.go
Introduces the 'package' definition and validation that #64 requires for its RPM resolution logic. This is introduced in a separate PR in order to reduce the complexity of #64.
=> Introduce 'package' definition and validation

pkg/build/templates/rebuild-iso.sh.tpl
Previously we assumed the partition offset would be fixed in the SLE Micro squashfs, but it seems to change. As we're not actually making partition changes, we can assume that we always take the original value from the user provided input file and re-use this.
=> Fixing partition offset in SLE-Micro.md5 file to be dynamic

Dockerfile, cmd/eib/main.go, go.mod, go.sum, pkg/image/context.go, pkg/kubernetes/artefact_downloader.go, pkg/kubernetes/artefact_downloader_test.go, pkg/kubernetes/script_installer.go
- Downloads RKE2 installer script at build time
- Introduces an easily mockable ScriptInstaller type which installs the script to the combustion directory
- Introduces an ArtefactDownloader type downloading the necessary files from Github release assets
- Adds basic support matrix validation of the RKE2 components
=> Add kubernetes installer package

docs/building-images.md, pkg/build/iso.go, pkg/build/iso_test.go, pkg/build/templates/rebuild-iso.sh.tpl, pkg/image/definition.go, pkg/image/definition_test.go, pkg/image/testdata/full-valid-example.yaml, pkg/image/validation.go, pkg/image/validation_test.go
This PR adds two new features:
1.  Unattended mode, where we skip the GRUB selection of install or boot from disk and automatically run the installation after 3 seconds (we may want to make this larger to enable users to override this). The default behaviour is to wait at the GRUB prompt to avoid data loss. For fully automated installs we need a way of overriding this.
2. Disk selection, where the user can tell the installer which disk to target (needs to be block special, e.g. /dev/sda), which has two primary benefits - firstly, if the system has more than one disk it allows the user to make this choice outside at image build time, not at boot time, and secondly, if the user has selected a disk to install to it forces the confirmation of wiping anything found on the target disk.
With …
=> Adding unattended mode and disk selection

docs/building-images.md, pkg/combustion/combustion.go, pkg/combustion/templates/09-time-setup.sh.tpl, pkg/combustion/time.go, pkg/combustion/time_test.go, pkg/image/definition.go, pkg/image/testdata/full-valid-example.yaml
This PR adds the ability to specify the timezone you wish your system to be setup with (see `timedatectl list-timezones`) and also allows the user to specify a list of `chronyPools` and `chronyServers`, which will populate a new file `/etc/chrony.d/eib-sources.conf` (removing the out of the box default SUSE NTP pool).
The setting of the timezone and chrony sources is executed early on in the boot process to ensure there's no issues with SSL, where later stages, e.g. SUMA/Elemental registration may break.
=> Adding support for setting timezone and chrony sources

pkg/image/context.go, pkg/kubernetes/artefact_downloader.go, pkg/kubernetes/artefact_downloader_test.go
- Splits the `kubernetes/` directory into `kubernetes/install` and `kubernetes/images`
- `kubernetes/install` will be used during combustion for the `INSTALL_RKE2_ARTIFACT_PATH` env variable necessary for airgap installs
- `kubernetes/images` will be used to transfer the airgap images to `/var/lib/rancher/rke2/agent/images/`
=> Split kubernetes artefacts into installers and images

docs/building-images.md, pkg/image/definition_test.go
Realised that I had forgotten to add definition tests for `OperatingSystem.Time` in #102 and also spotted a typo that I introduced to the docs in #98
=> Adding definition tests for OperatingSystem.Time and fixing typo in docs

go.mod, go.sum, pkg/http/download.go, pkg/kubernetes/artefact_downloader.go
- Drops the concurrent download pattern for kubernetes artefacts since:
- Downloads are limited per bandwidth
- Downloads in chunks are currently not utilized
- The chosen progress bar package supports a single output only, however, it's one of the most well documented and supported options
- Other progress bar implementations are too complex for what they provide as well as require some kind of a pool of bars which is then harder to reuse where necessary
- Introduces a progress bar functionality for file downloads
- Tested with Kubernetes artefacts implementation:
```
Generating image customization components...
Identifier ................... [SUCCESS]
Custom Files ................. [SKIPPED]
Network ...................... [SKIPPED]
Users ........................ [SUCCESS]
Rpm …
```
=> Introduce progress bar in downloads

docs/building-images.md, pkg/combustion/combustion.go, pkg/combustion/proxy.go, pkg/combustion/proxy_test.go, pkg/combustion/templates/08-proxy-setup.sh.tpl, pkg/image/definition.go, pkg/image/definition_test.go, pkg/image/testdata/full-valid-example.yaml
This PR adds support for setting the system-wide proxy servers. It takes care of the following in `/etc/sysconfig/proxy`:
1. If either `httpProxy` or `httpsProxy` are set, it forces `PROXY_ENABLED="yes"`
2. If `httpProxy` is set, it will setup `HTTP_PROXY="<httpProxy>"`
3. If `httpsProxy` is set, it will setup `HTTPS_PROXY="<httpsProxy>"`
4. If `noProxy` is set, it will setup `NO_PROXY="<noProxy>"` (if left omitted it will leave default, `localhost, 127.0.0.1`).
This was tested via Squid and works exactly as required. This likely needs to be setup very early in the boot-up procedure as many items may require proxy.
=> Adding support for setting the system-wide proxy servers

docs/building-images.md, pkg/combustion/combustion.go, pkg/combustion/keymap.go, pkg/combustion/keymap_test.go, pkg/combustion/templates/13-keymap-setup.sh.tpl, pkg/image/definition.go, pkg/image/definition_test.go, pkg/image/testdata/full-valid-example.yaml
This PR adds an additional feature that supports the configuration of the systems virtual console keymap. A list of available keymaps can be found via `localectl list-keymaps`. Without this feature, the system default appears to be `us`, but the system sometimes complains that one isn't set (although this seems to not be a significant issue).
=> Adding support for setting the system keymap

pkg/rpm/resolver/templates/prepare-base.sh.tpl
Move away from using `gzip` when creating the SLE Micro archive when running RPM resolution. Currently we are using `gzip` to create an archive for the data passed by [virt-tar-out](https://github.com/suse-edge/edge-image-builder/blob/main/pkg/rpm/resolver/templates/prepare-base.sh.tpl#L36).
The problem here is that `gzip` is working on a single CPU thread which makes it very slow when archiving large data.
[pigz](https://zlib.net/pigz/) ([doc](https://zlib.net/pigz/pigz.pdf)) offers a `gzip` that can run in parallel. 
Using `pigz` dramatically decreases the time needed to create the SLE Micro archive which is used as a base image for the RPM resolver.
=> Use pigz instead of gzip for base image archive

pkg/combustion/kubernetes.go, pkg/combustion/kubernetes_test.go, pkg/combustion/templates/15-rke2-installer.sh.tpl, pkg/image/context.go, pkg/image/definition.go, pkg/image/definition_test.go, pkg/image/testdata/full-valid-example.yaml, pkg/image/validation.go, pkg/image/validation_test.go, pkg/kubernetes/artefact_downloader.go, pkg/kubernetes/artefact_downloader_test.go
- Removes CNI and multus configurations from EIB definition
- Uses a Kubernetes (RKE2) configuration file instead
- Uses Cilium as a default CNI if one is not provided
- Drops vSphere support
=> Drop Kubernetes options from the EIB definition in favour of RKE2 config file

README.md, cmd/eib/main.go, pkg/image/validation/image.go, pkg/image/validation/image_test.go, pkg/image/validation/kubernetes.go, pkg/image/validation/kubernetes_test.go, pkg/image/validation/os.go, pkg/image/validation/os_test.go, pkg/image/validation/registry.go, pkg/image/validation/registry_test.go, pkg/image/validation/validation.go, pkg/image/validation/validation_test.go
Previous output, which only displayed the first validation failure encountered:
```
2024/01/19 19:53:41 CLI arguments could not be parsed: parsing image definition file iso-image.yaml: error validating definition file: error validating image: arch not defined
```
New output:
```
Image definition validation found the following errors:
Image
The 'imageType' field must be one of: iso, raw
The 'arch' field is required in the 'image' section.
The 'outputImageName' field is required in the 'image' section.
The specified base image 'oops.iso' cannot be found.
Operating System
Duplicate kernel argument found: foo
Systemd enable list contains duplicate entries: bar
Systemd conflict found, 'foo' is both enabled and disabled.
User 'jdob' must have either a password or SSH key.
The suma 'host' field …
```
=> Migrated the CLI to use the new validation framework

pkg/combustion/rpm_test.go, pkg/image/definition.go, pkg/image/definition_test.go, pkg/image/testdata/full-valid-example.yaml, pkg/image/validation.go, pkg/image/validation/os.go, pkg/image/validation/os_test.go, pkg/image/validation_test.go, pkg/rpm/resolver/resolver.go
Refactoring `AdditionalRepos` from a `[]string` to a struct was discussed in #64. 
By adopting this structure we get the flexibility to easily add additional repo configurations whenever the need for such configuration arises.
Note: This PR is a prerequisite for the RPM resolver GPG validation logic PR that is currently being implemented.
=> Refactor "AdditionalRepos" field to a struct

pkg/build/build.go
I accidentally bumped into the bug by running two builds too close to each other (only possible if the validation fails).
=> fixed super unlikely timing bug

cmd/eib/main.go, pkg/log/audit.go
Prior to this patch, the output when running EIB with a definition file that doesn't exist is:
```
2024/01/23 15:42:18 CLI arguments could not be parsed: parsing image definition file raw-image.yaml: image definition file "raw-image.yaml" cannot be read: open /eib/raw-image.yaml: no such file or directory
```
This patch uses a similar approach as with image validation errors to display more user-friendly messages in the case of most user errors. The following are examples of various ways that EIB can fail to even start building an image:
_Note: This is the only step that occurs prior to initializing logging_
```
$ podman run --rm -it -v ~/Code/eib/:/not-there eib:dev /bin/eib -config-file ./raw-simple.yaml -config-dir /eib -build-dir /eib/_build
The specified image configuration directory …
```
=> Cli UX Improvements

cmd/eib/main.go, pkg/cache/cache.go, pkg/cache/cache_test.go, pkg/http/download.go, pkg/http/download_integration_test.go, pkg/http/download_test.go, pkg/kubernetes/artefact_downloader.go, pkg/registry/manifests.go
- Introduces basic file caching mechanism
- Uses a `cache` directory in the root build dir
Examples:
```
suse-edge380@edge380:~/atanas/eib> ll _build/
total 0
drwxr-xr-x 1 suse-edge380 users 298 Jan 26 07:12 build-Jan26_12-11-25
drwxr-xr-x 1 suse-edge380 users 298 Jan 26 07:12 build-Jan26_12-12-23
drwxr-xr-x 1 suse-edge380 users 298 Jan 26 07:14 build-Jan26_12-13-48
drwxr-xr-x 1 suse-edge380 users 312 Jan 26 07:14 cache
```
```
suse-edge380@edge380:~/atanas/eib> ll _build/cache/
total 2349668
-rw-r--r-- 1 suse-edge380 users  28110568 Jan 26 07:11 11240812976698639811
-rw-r--r-- 1 suse-edge380 users      3626 Jan 26 07:14 12598788008564349138
-rw-r--r-- 1 suse-edge380 users 398552443 Jan 26 07:14 12731077518120169689
-rw-r--r-- 1 suse-edge380 users  28127289 Jan 26 07:14 …
```
=> Introduce file caching

go.mod, go.sum, pkg/kubernetes/cluster.go, pkg/kubernetes/cluster_test.go
- Generate a UUID as a [short](https://docs.k3s.io/cli/token#short) cluster token for RKE2 clusters
=> Use UUID for RKE2 cluster token

pkg/combustion/kubernetes.go, pkg/combustion/kubernetes_integration_test.go, pkg/combustion/registry.go, pkg/combustion/registry_test.go, pkg/combustion/templates/15-rke2-multi-node-installer.sh.tpl, pkg/combustion/templates/15-rke2-single-node-installer.sh.tpl, pkg/combustion/templates/registries.yaml.tpl
This is the finale in the manifest deployment saga, excluding helm charts. This includes the final piece of the puzzle for actually using all of the previous merged implementations for completely air-gapped manifest deployment.
=> Complete air-gapped manifest deployment

docs/building-images.md, pkg/build/iso.go, pkg/build/iso_test.go, pkg/combustion/templates/09-time-setup.sh.tpl, pkg/combustion/time.go, pkg/combustion/time_test.go, pkg/image/definition.go, pkg/image/definition_test.go, pkg/image/testdata/full-valid-example.yaml, pkg/image/validation/os.go, pkg/image/validation/os_test.go
Includes:
* Moving the two installation-related fields (`installDevice` and `unattended`) under their own section called `isoInstallation`
* Moved the two NTP-related fields (`chronyServers` and `chronyPools`) under their own section called `ntp`, removing the `chrony` prefix in the process
=> Updates to the image definition for 1.0 release - Part 1

docs/building-images.md, pkg/image/definition.go, pkg/image/testdata/full-valid-example.yaml
I only changed the YAML key; given the struct embedding it was redundant in the code.
I also snuck in the doc fixes for the previous noProxy change.
=> renamed package registration code to include 'scc'

pkg/image/definition.go, pkg/image/testdata/full-valid-example.yaml
I only changed the definition spelling; internally it's anything goes on spelling.
=> renamed API-facing initializer attribute for consistency

pkg/combustion/templates/15-rke2-multi-node-installer.sh.tpl, pkg/combustion/templates/15-rke2-single-node-installer.sh.tpl
There seems to be an issue where Cilium cannot be installed on SLE Micro with the out of the box rke2+rke2-selinux configuration. An issue was raised back in 2022 for a similar issue (https://github.com/rancher/rke2/issues/3561) and it was fixed by manually creating the directory during the rke2-selinux post-install RPM script. (https://github.com/rancher/rke2-selinux/pull/29/files).
However, this line: https://github.com/rancher/rke2-selinux/blob/master/policy/slemicro/rke2-selinux.spec#L66 isn't triggered during Combustion, so the directory isn't created and hence we run into the originally reported issue. This change forces the creation of the directory at combustion time, and hence allows the policy enhancement from the original fix to take effect as expected …
=> Creating /opt/cni directory for SELinux issues

pkg/combustion/kubernetes_test.go, pkg/combustion/templates/15-k3s-multi-node-installer.sh.tpl, pkg/combustion/templates/15-k3s-single-node-installer.sh.tpl
In the original version we were moving the k3s binaries to `/opt/k3s/` which doesn't match the behaviour of rke2 (`/opt/rke2/bin/`), so this brings it inline so we can push the latest requirements into k3s-selinux in a consistent way.
=> Moving the k3s bin directory to /opt/k3s/bin/

pkg/combustion/kubernetes_test.go, pkg/combustion/templates/15-k3s-multi-node-installer.sh.tpl, pkg/combustion/templates/15-k3s-single-node-installer.sh.tpl
In https://github.com/k3s-io/k3s-selinux/pull/58 it was correctly pointed out that in the k3s installer they explicitly use `/opt/bin/` for the k3s bin directory (https://github.com/k3s-io/k3s/blob/master/install.sh#L227-L234). This unfortunately doesn't have consistency with rke2, but we can't break existing installer functionality, nor impact potential upgrade concerns. This change modifies to suit.
=> Reverting back to /opt/bin for k3s to align with k3s install script

Dockerfile
- Reorders builder image layers
- Only includes source code copies
- Utilises `RUN --mount=type=cache` option
=> Improve Dockerfile layer caching

docs/building-images.md, docs/installing-packages.md, pkg/image/definition.go, pkg/image/definition_test.go, pkg/image/testdata/full-valid-example.yaml, pkg/rpm/resolver/resolver.go, pkg/rpm/resolver/templates/Dockerfile.tpl
- Adjusts the templating to allow unsigned RPM repositories
- Example 1: 
```
AddRepo:
- URL: https://rpm.rancher.io/rke2/stable/common/slemicro/noarch
Unsigned: true
- URL: https://download.nvidia.com/suse/sle15sp5/
NoGPGCheck: false
```
=>
```
RUN zypper ar --gpgcheck-allow-unsigned-repo -f https://rpm.rancher.io/rke2/stable/common/slemicro/noarch addrepo0
RUN zypper ar  -f https://download.nvidia.com/suse/sle15sp5/ addrepo1
```
- Example 2:
```
AddRepo:
- URL: https://rpm.rancher.io/rke2/stable/common/slemicro/noarch
Unsigned: true
- URL: https://download.nvidia.com/suse/sle15sp5/
NoGPGCheck: true
```
=>
```
RUN zypper ar --no-gpgcheck -f https://rpm.rancher.io/rke2/stable/common/slemicro/noarch addrepo0
RUN zypper ar --no-gpgcheck -f https://download.nvidia.com/suse/sle15sp5/ addrepo1 …
```
=> Support unsigned RPM repositories

Dockerfile, docs/building-images.md, pkg/build/raw.go, pkg/build/raw_test.go, pkg/build/templates/modify-raw-image.sh.tpl, pkg/image/definition.go, pkg/image/testdata/full-valid-example.yaml, pkg/image/validation/os.go, pkg/image/validation/os_test.go
This PR enables the user to specify a desired raw disk image size, this has two key benefits, firstly ensuring that the initial disk image is resized to accommodate the combustion directory accordingly, and secondly to set the size of the partitions for its first boot, noting that if there's any additional space the system will resize to the maximum block size automatically. This change also helps with automated testing and virtual setups, where there's no physical block device that's being used.
=> Adding support for specifying the desired raw disk size

docs/building-images.md, pkg/build/iso.go, pkg/build/iso_test.go, pkg/image/definition.go, pkg/image/definition_test.go, pkg/image/testdata/full-valid-example.yaml, pkg/image/validation/os.go, pkg/image/validation/os_test.go
When `rawConfiguration` was added, we talked about renaming this field to match for consistency.
=> renamed isoInstallation section to isoConfiguration

pkg/image/validation/os.go, pkg/image/validation/os_test.go
Remove the validation for the `packageList` RPM resolution property.
Use-case for this is that we want to be able to install packages on openSUSE images without having to provide a third-party repository or a registration code.
=> Remove package list validation

pkg/image/validation/api_version.go, pkg/image/validation/api_version_test.go, pkg/image/validation/validation.go
I'm writing up a design doc detailing the rules we're going to follow when it comes to changing the schema version, but in the interest of getting the first RC built, I'm going to do that in a separate PR in case we go back and forth on the phrasing and handling.
=> added basic schema version validation for 1.0

pkg/image/definition.go, pkg/image/definition_test.go
- Rejects unknown / mistyped fields in the image definition
- A better validation / schema versioning approach can be revisited later (from a UX perspective)
=> Reject unknown image definition fields

pkg/combustion/rpm.go
Add a warning log to the RPM resolution process when a `packageList` has been provided without a `sccRegistrationCode` or and `additionalRepos` entry
Config:
```yaml
operatingSystem:
packages:
packageList:
- git 
```
Sample output:
```shell
Generating image customization components...
Identifier ................... [SUCCESS]
Custom Files ................. [SKIPPED]
Time ......................... [SKIPPED]
Network ...................... [SKIPPED]
Users ........................ [SUCCESS]
Proxy ........................ [SKIPPED]
WARNING: No SUSE registration code or additional repositories provided, package resolution may fail if you're using SLE Micro as the base image
Resolving package dependencies...
```
=> Add warning message when missing registration code and additional repos for packageList

pkg/combustion/registry_test.go, pkg/combustion/templates/26-embedded-registry.sh.tpl
Instead of mounting `/usr/local/` we instead put in the hauler binary in `/opt/hauler/`
=> Change location of Hauler bin

pkg/combustion/registry.go
Fixes an issue where the embedded artifact registry is not configured when only local manifests are specified.
Closes #209
=> Check if local manifests dir is configured

RELEASE_NOTES.md, docs/building-images.md, pkg/combustion/combustion.go, pkg/combustion/network.go, pkg/combustion/network_test.go
- Use `network/configure-network.sh` script to configure the network @ Combustion phase if present
- Use any other `network/` files to generate configurations using nmc
=> Allow custom network configuration scripts

Dockerfile, pkg/combustion/registry.go
- Drops Hauler Github release references in favour of RPM installation
- Closes https://github.com/suse-edge/edge-image-builder/issues/203 (the RPM is already using v1.0.0)
=> Install Hauler from RPM

Dockerfile
Docker layers are only rebuilt if necessary, starting at the lowest one with a change. With our previous division, adding the SUSE Edge repo and calling `refresh` was in its own layer separate from the package install calls. While uncommon, this leaves the chance to use stale repo metadata from a cached layer. These two operations should be in the same layer since they are used in conjunction with each other to make sure the metadata and actual RPMs available in the repo match.
=> consolidate zypper repo add and install layers

Dockerfile, README.md, docs/design/pkg-resolution.md
closes: #197 
I tested it and it works like Steve suggested, that we don't need to indicate `/bin/eib` in the podman run line. `ENTRYPOINT` makes more sense here since the only argument it includes is the location of the executable, which isn't something that changes.
=> 197 - Changed Dockerfile to use ENTRYPOINT instead of CMD

go.mod, pkg/cli/build/build.go, pkg/mount/mount.go, pkg/mount/mount_test.go, pkg/rpm/resolver/resolver.go
This PR offers the functionality to disable any automatic container volume mounts configured through the [`mounts.conf`](https://github.com/containers/common/blob/main/docs/containers-mounts.conf.5.md) configuration logic offered by the [`containers/common`](https://github.com/containers/common/tree/main) shared library. 
This is a non-invasive way of fixing the RPM resolution problem that occurs when the EIB image is using BCI as base. In the TL;DR you can find a detailed explanation of the problem, what was tried and why the current approach was taken.. 
During the RPM resolution process, when an `sccRegistrationCode` is provided, the RPM resolver attempts to register the system to `https://scc.suse.com` using `SUSEConnect`. However, if the EIB image runs on top of …
=> Disable Podman auto-mounts when running RPM resolution

docs/design/default-mounts-disablement.md
As discussed in [#235](https://github.com/suse-edge/edge-image-builder/pull/235#issuecomment-1971215972), I am adding the description as a design doc for EIB.
=> Add design doc for the disablement of the default mounts.conf file

RELEASE_NOTES.md, pkg/fileio/file_io.go
There's potentially a larger fix needed to allow multiple extensions to be specified in a single call. But for now, reducing this to debug should help prevent user confusion of why they were being "warned" about a situation that isn't necessarily a problem.
closes: #239
=> 239 - Reduce log message for files not matching the given extension

RELEASE_NOTES.md, pkg/rpm/resolver/resolver.go, pkg/rpm/resolver/templates/Dockerfile.tpl, pkg/rpm/resolver/templates/rpm-resolution.sh.tpl
If the RPM resolution run fails before getting to the registration data [cleanup](https://github.com/suse-edge/edge-image-builder/blob/main/pkg/rpm/resolver/templates/Dockerfile.tpl#L66), the registration stays visible on SCC. Users would then have to manually go and remove the failed system from their subscription. This bad user experience is fixed by the suggested changes in this PR.
**What does this PR introduce:**
1. Main resolution logic has been moved from the resolver image Dockerfile to a bash script
2. Script is executed through the resolver Dockerfile
**What does this achieve**
By doing this, we can ensure that we [`trap`](https://man7.org/linux/man-pages/man1/trap.1p.html) the `suseconnect -d` command inside the bash script, ensuring that it will always be executed no matter …
=> [BUG FIX] SCC registration is not cleaned up if RPM resolution fails

examples/README.md, examples/iso/basic.yaml, examples/raw/basic.yaml
I don't think this is the final form it will take once we get to more complex examples, but I would rather start small and iterate instead of trying to boil the ocean on the first try. The important part is that we don't have a directory of a bunch of files with no description around them outside of the filename, since that can be become pretty useless quickly. The goal was to describe in text what the definition does so users can find what they need without needing to be experts in our schema.
=> initial attempt at an examples directory

RELEASE_NOTES.md, pkg/combustion/custom.go, pkg/combustion/custom_test.go
- Uses the input custom files' permissions when copying to the combustion directory
- Closes https://github.com/suse-edge/edge-image-builder/issues/272
=> Keep custom files' permissions

README.md, RELEASE_NOTES.md, docs/design/pkg-resolution.md, examples/README.md, pkg/build/build.go, pkg/build/build_test.go, pkg/cli/build/build.go
- Omitting `--build-dir` no longer defaults to using a temporary directory within the container - it is now implicitly set to `<config-dir>/_build`
- Closes https://github.com/suse-edge/edge-image-builder/issues/284
=> Change default behaviour for --build-dir

docs/building-images.md
* Adds an example for the `rawConfiguration` property
* Adds a note regarding building RAW images with Kubernetes configuration
=> Add note to Kubernetes documentation for RAW images

README.md, RELEASE_NOTES.md, docs/design/pkg-resolution.md, examples/README.md, pkg/cli/cmd/build.go
- The `--config-dir` flag is no longer required and now defaults to `/eib`
- Closes https://github.com/suse-edge/edge-image-builder/issues/303
=> Change default behaviour for --config-dir

RELEASE_NOTES.md, pkg/helm/helm.go, pkg/helm/helm_test.go
=> Helm parse fix

RELEASE_NOTES.md, pkg/combustion/elemental.go, pkg/combustion/elemental_test.go, pkg/combustion/templates/31-elemental-register.sh.tpl
In this PR we move Elemental register to a systemd unit instead, that attempts to continually register rather than halting the boot and dropping to an emergency shell that requires manual intervention. We also move the package repo to the *other* temporary repo for 5.5 maintenance from OBS. This will get replaced with the proper repo in the coming days, but this unblocks folks wanting to try EIB+Elemental in the meantime.
Fixes: #315
=> Moved Elemental register to a systemd unit and updated temporary Elemental RPM location

RELEASE_NOTES.md, pkg/podman/listener.go, pkg/podman/podman.go
Currently there is a race-condition that can happen where we start the [API Listener](https://github.com/suse-edge/edge-image-builder/blob/main/pkg/podman/listener.go#L29) and immediately attempt to make a [connection](https://github.com/suse-edge/edge-image-builder/blob/main/pkg/podman/podman.go#L44) with Podman. 
This sometimes results in the following error:
```bash
creating new podman connection: unable to connect to Podman socket: Get "http://d/v4.8.3/libpod/_ping": dial unix /run/podman/podman.sock: connect: no such file or directory
```
Mainly this happens, because we do not give enough time for the API Listener to create its `podman.sock` file. 
This PR introduces a waiting mechanism that waits for the `podman.sock` file to be created. The wait timeout for this file is 15 seconds, …
=> [Bug Fix] Add wait mechanism for Podman's API Listener service

README.md, RELEASE_NOTES.md, cmd/eib/main.go, pkg/cli/build/build.go, pkg/cli/build/validate.go, pkg/cli/cmd/build.go, pkg/cli/cmd/error.go, pkg/cli/cmd/flags.go, pkg/cli/cmd/validate.go, pkg/log/audit.go, pkg/log/log.go
- Introduces new `validate` subcommand
- Drops the `--validate` argument from the `build` subcommand
- Improves CLI error handling
- Closes https://github.com/suse-edge/edge-image-builder/issues/302
**Successful validation:**
```
suse-edge380@edge380:~/atanas/eib> podman run --rm -it -v /home/suse-edge380/atanas/eib:/eib eib:dev validate --definition-file k3s-single-node.yaml
Checking image config dir...
Parsing image definition...
Validating image definition...
The specified image definition is valid.
```
**Unsuccessful validation:**
```
suse-edge380@edge380:~/atanas/eib> podman run --rm -it -v /home/suse-edge380/atanas/eib:/eib eib:dev validate --definition-file k3s-single-node.yaml
Checking image config dir...
Parsing image definition...
Validating image definition...
Image definition …
```
=> Add validate subcommand

RELEASE_NOTES.md, pkg/build/build.go, pkg/build/build_test.go, pkg/build/iso.go, pkg/build/raw.go, pkg/build/templates/modify-raw-image.sh.tpl, pkg/build/templates/rebuild-iso.sh.tpl, pkg/cli/build/build.go, pkg/combustion/combustion.go, pkg/combustion/combustion_test.go, pkg/combustion/kubernetes.go, pkg/combustion/kubernetes_integration_test.go, pkg/combustion/kubernetes_test.go, pkg/combustion/registry.go, pkg/combustion/registry_test.go, pkg/combustion/rpm.go, pkg/combustion/rpm_test.go, pkg/combustion/script.go, pkg/combustion/script_test.go, pkg/combustion/templates/10-rpm-install.sh.tpl, pkg/combustion/templates/26-embedded-registry.sh.tpl, pkg/combustion/templates/k3s-multi-node-installer.sh.tpl, pkg/combustion/templates/k3s-single-node-installer.sh.tpl, pkg/combustion/templates/rke2-multi-node-installer.sh.tpl, pkg/combustion/templates/rke2-single-node-installer.sh.tpl, pkg/combustion/templates/script-base.sh.tpl, pkg/image/context.go
- Moves the larger files for the RPM, Kubernetes and Embedded Registry components out of the combustion directory into a new artefacts one
- Network component is intentionally skipped due to it only using a couple of MBs (~5)
- Custom component is intentionally skipped due to:
- Scripts ordering
- Scripts referencing other custom files
- Assumption that the files will not be that large
- Potentially introducing https://github.com/suse-edge/edge-image-builder/issues/200 
- Closes https://github.com/suse-edge/edge-image-builder/issues/319
=> Introduce artefacts directory

RELEASE_NOTES.md, pkg/combustion/helm.go, pkg/env/env.go
- Extracts a SUSE Edge chart repository variable to a new `env` package
- Modifying the variable is as simple as adding a flag to the build:
```
MODULE=github.com/suse-edge/edge-image-builder
go build -ldflags "-X $MODULE/pkg/env.SUSEEdgeRepository=<repository-url>" ./cmd/eib
```
- Closes https://github.com/suse-edge/edge-image-builder/issues/233
=> Extract configurable Helm chart repository variable

RELEASE_NOTES.md, pkg/combustion/templates/k3s-multi-node-installer.sh.tpl, pkg/combustion/templates/rke2-multi-node-installer.sh.tpl
- Evaluates both `/etc/hostname` and `/proc/sys/kernel/hostname` as sources of hostnames
- Tried using `hostnamectl` but it is not available during the combustion phase
- Closes https://github.com/suse-edge/edge-image-builder/issues/258
=> Fix hostname evaluation

RELEASE_NOTES.md, pkg/image/validation/kubernetes.go, pkg/image/validation/kubernetes_test.go
=> Fix Helm chart validation bug

RELEASE_NOTES.md, pkg/combustion/registry.go
A progress bar is now shown when populating the embedded artifact registry to demonstrate progress. Previously, the embedded artifact registry would just run in the background and it was difficult to tell if it was still going or if there was something wrong.
Example output:
```
Generating image customization components...
Identifier ................... [SUCCESS]
Custom Files ................. [SUCCESS]
Time ......................... [SKIPPED]
Network ...................... [SKIPPED]
Groups ....................... [SKIPPED]
Users ........................ [SUCCESS]
Proxy ........................ [SKIPPED]
Rpm .......................... [SKIPPED]
Systemd ...................... [SKIPPED]
Elemental .................... [SKIPPED]
Suma ......................... [SKIPPED]
Populating Embedded …
```
=> Embedded artifact registry progress bar

RELEASE_NOTES.md, pkg/registry/helm.go, pkg/registry/helm_test.go
=> Fix Helm chart OCI registry handling

RELEASE_NOTES.md, pkg/helm/helm.go, pkg/helm/helm_test.go
- Fixes an issue where the presence of `---` within a resource would falsely split it in half
- Fixes an issue where the `source` was not properly parsed
- Closes https://github.com/suse-edge/edge-image-builder/issues/362
=> Fix helm template parsing

RELEASE_NOTES.md, pkg/helm/helm.go
- Adjusts the Helm build directory to use chart subdirectories
- Closes https://github.com/suse-edge/edge-image-builder/issues/365
- New layout:
```
suse-edge380@edge380:~/atanas/eib> ls _build/build-Apr09_16-05-27/helm -l
total 0
drwxr-xr-x 1 suse-edge380 users 26 Apr  9 12:05 cdi
drwxr-xr-x 1 suse-edge380 users 48 Apr  9 12:05 cert-manager
drwxr-xr-x 1 suse-edge380 users 28 Apr  9 12:05 core
drwxr-xr-x 1 suse-edge380 users 38 Apr  9 12:05 elemental
drwxr-xr-x 1 suse-edge380 users 68 Apr  9 12:05 elemental-operator-chart
drwxr-xr-x 1 suse-edge380 users 78 Apr  9 12:05 elemental-operator-crds-chart
drwxr-xr-x 1 suse-edge380 users 68 Apr  9 12:05 endpoint-copier-operator
drwxr-xr-x 1 suse-edge380 users 36 Apr  9 12:05 kubevirt
drwxr-xr-x 1 suse-edge380 users 76 Apr  9 12:05 …
```
=> Fix locating downloaded Helm charts

RELEASE_NOTES.md, pkg/kubernetes/cluster.go, pkg/kubernetes/cluster_test.go
- Set agents' selinux config option to the one provided for servers
- Closes https://github.com/suse-edge/edge-image-builder/issues/374
=> Use same SELinux config option for both server and agent nodes

RELEASE_NOTES.md, pkg/image/validation/os.go, pkg/image/validation/os_test.go
- The conditionals to check the OS section in the definition file was left far behind all of the current functionality
- Those are now completely removed in order not to have them forgotten in the future
- Closes https://github.com/suse-edge/edge-image-builder/issues/383
=> Drop OS validation criteria

RELEASE_NOTES.md, pkg/combustion/certificates.go, pkg/combustion/certificates_test.go
This handling matches what we do in other cases for directories in the image configuration directory. Eventually we should add these sorts of checks to the validation step, but for now this is consistent with how it's handled elsewhere in EIB.
Closes: #372
=> added check for empty certificates directory

RELEASE_NOTES.md, pkg/combustion/registry_test.go, pkg/registry/helm.go, pkg/registry/helm_crd.go
Added annotations to Helm Charts deployed by EIB.
Examples:
```
localhost:~ # /var/lib/rancher/rke2/bin/kubectl describe helmchart -n kube-system endpoint-copier-operator
Name:         endpoint-copier-operator
Namespace:    kube-system
Labels:       objectset.rio.cattle.io/hash=dff2ee5284ff87febe8538225e1f44cd38d991ea
Annotations:  helmcharts.cattle.io/managed-by: helm-controller
objectset.rio.cattle.io/applied:
H4sIAAAAAAAA/4yTQW/TQBCF/wqa83rtOAmklji0DVWjihwoTQS38Xpib7zeNbtjQ1vlv6MtpS2Ctvg2mudv3jx7bgF7vSEftLNQQEOmkwqZDUnt0nECAlptKyjgnEx32qBnENARY4...
objectset.rio.cattle.io/id:
objectset.rio.cattle.io/owner-gvk: k3s.cattle.io/v1, Kind=Addon
objectset.rio.cattle.io/owner-name: endpoint-copier-operator
objectset.rio.cattle.io/owner-namespace: kube-system
repositoryUrl: …
```
=> Add origin metadata to HelmChart CRs

examples/README.md, examples/iso/basic.yaml
This commit updates the readme as well as the corresponding definition file, replacing the image SLE-Micro.x86_64-5.5.0-Default-SelfInstall-GM.install.iso with SLE-Micro.x86_64-5.5.0-Default-SelfInstall-GM2.install.iso as documented in SUSE Edge EIB quickstart. [0]
[0] https://suse-edge.github.io/quickstart-eib.html#id-creating-the-image-configuration-directory
=> Update base image in examples readme and definition file

RELEASE_NOTES.md, pkg/build/raw.go, pkg/image/definition.go, pkg/image/definition_test.go, pkg/image/validation/os.go, pkg/image/validation/os_test.go
- Prevents some of the builds which would result in a combustion failure
- Running a plethora of tests shows the following:
- Including custom files (313 MB in total) requires expanding the base image (2188 MB) to 2502 MB (2188 + 313 + 1)
- Including custom files (313 MB) + k3s (219 MB) (533 MB in total) requires expanding the base image (2188) to 3000 MB to bypass the combustion failure (but run into k3s failure) and to 4500 MB to properly start up
- Including custom files (313 MB) + RKE2 (1126 MB) (1439 MB in total) requires expanding the base image (2188 MB) to roughly 5000 to bypass the combustion failure (but running into RKE2 failure) and to 10 000 MB to properly start up
- Further testing and more complex calculations need to take place for making good estimations for suggestions / …
=> Fail if build artefacts size exceeds the available space on RAW images

RELEASE_NOTES.md, docs/building-images.md, pkg/combustion/registry_test.go, pkg/helm/helm.go, pkg/helm/helm_test.go, pkg/image/definition_test.go, pkg/image/testdata/full-valid-example.yaml, pkg/image/validation/kubernetes_test.go, pkg/registry/helm_test.go
- Removes the expectation that the Helm chart name is part of the registry URL
- Closes https://github.com/suse-edge/edge-image-builder/issues/405
Given the following API definition:
```
kubernetes:
helm:
charts:
- name: apache
repositoryName: bitnami
version: 10.7.0
targetNamespace: web
createNamespace: true
installationNamespace: kube-system
repositories:
- name: bitnami
url: oci://registry-1.docker.io/bitnamicharts
network:
apiVIP: 192.168.122.133
version: v1.28.7+rke2r1
```
we observe the following behaviour for `helm pull`:
```
suse-edge380@edge380:~/atanas/eib> cat _build/build-Apr18_10-18-28/helm-pull.log
command: /usr/bin/helm pull oci://registry-1.docker.io/bitnamicharts/apache --version 10.7.0 --destination /eib/_build/build-Apr18_10-18-28/helm/apache
Pulled: …
```
=> Fix OCI repository URL handling

RELEASE_NOTES.md, docs/building-images.md, pkg/combustion/registry_test.go, pkg/helm/helm.go, pkg/helm/helm_test.go, pkg/image/definition_test.go, pkg/image/testdata/full-valid-example.yaml, pkg/image/validation/kubernetes_test.go, pkg/registry/helm_test.go
* Fix OCI repository URL handling
* Use url.JoinPath to construct the repository name
* Update release notes
* Set release notes for v1.0.1
---------
=> [Release 1.0] Fix OCI repository URL handling

.github/workflows/build_image.yaml
This commit introduces a new workflow to attempt building EIB container image for prs and pushes to verify the image is buildable.
=> Add image build workflow on prs and pushes

RELEASE_NOTES.md, pkg/combustion/custom.go, pkg/combustion/custom_test.go
=> set custom scripts to executable, but custom files retain their existing permissions

RELEASE_NOTES.md, pkg/helm/helm.go, pkg/registry/manifests.go, pkg/registry/manifests_test.go, pkg/registry/testdata/sample-crd.yaml
Closes #442 
Putting this up for review but I don't plan to merge until I've tested some air-gapped cases to make sure everything is still working as expected.
=> Helm Template Changes

RELEASE_NOTES.md, pkg/combustion/elemental_test.go, pkg/combustion/templates/31-elemental-register.sh.tpl
Currently, SLE Micro hosts that register against Elemental (and are provisioned via EIB) cannot utilise the `elemental.cattle.io/resettable: 'true'` capability to wipe Kubernetes cluster information and restore the machine to the inventory so it can be re-used. The current behaviour is that the node is deleted, and manual action needs to take place to clean up data and re-register the machine, which is undesirable.
In https://github.com/rancher/elemental-operator/pull/731 I've made a suggestion on how we can implement OS-agnostic system markers that can be watched to trigger any desired cleanup actions, bypassing the need to have Elemental be concerned with the type of OS being utilised. As part of Edge we should look for this marker and take appropriate action. In this PR we introduce a …
=> Adding Elemental Reset capabilities to nodes provisioned via EIB

pkg/combustion/templates/26-embedded-registry.sh.tpl
Make embedded-registry script reentrant since it would be failed if `/opt/hauler` already exists.
=> Make embedded-registry script reentrant

RELEASE_NOTES.md, pkg/registry/manifests.go, pkg/registry/manifests_test.go, pkg/registry/testdata/sample-crd.yaml
=> [Release 1.0] Only extract container images from specific Kubernetes objects when parsing Helm charts

RELEASE_NOTES.md, docs/building-images.md, pkg/combustion/combustion.go, pkg/combustion/osfiles.go, pkg/combustion/osfiles_test.go, pkg/combustion/templates/19-copy-os-files.sh
=> added ability to copy files into the built image's filesystem

Dockerfile
Temporariliy downgrade golang to version 1.22-1.11.6 to prevent glibc mismatch
fixes #483
=> Downgrade golang BCI to fix glibc mismatch

Dockerfile
Upgrade to OpenSuse Leap to version 15.6 and upgrade golang BCI to match the glibc-version (2.38).
closes #476
=> Upgrade OpenSuse Leap from version 15.5 to version 15.6

pkg/build/templates/rebuild-iso.sh.tpl
Replaces the sed expression for appending the rd.kiwi.oem.installdevice kernel parameter for unattended install.
fixes #487
Note: the edge-image-builder code base contains the 'ignition.platform' sed expression in other places. These create other incompatibilities with SL Micro 6. KernelArgs is one example. This contribution only covers the InstallDevice issue.
=> Replace sed expression for InstallDevice to support unattended install on SL Micro 6

Dockerfile, RELEASE_NOTES.md, pkg/build/raw.go, pkg/build/raw_test.go, pkg/build/templates/modify-raw-image.sh.tpl, pkg/eib/eib.go, pkg/rpm/resolver/base.go, pkg/rpm/resolver/resolver.go, pkg/rpm/resolver/templates/prepare-tarball.sh.tpl, pkg/rpm/resolver/templates/rpm-resolution.sh.tpl
Adds support for building Arm images on an Arm machine
Cross architecture build capabilities (building Arm images on x86_64 and vice versa) will come in a future PR
Closes: #193
=> Arm support

.github/dependabot.yaml, Dockerfile
Adds a "docker" ecosystem to Dependabot to automatically create pull requests for base container image updates.
Also adds a RUN instruction to the Dockerfile to verify the compatibility between the Golang BCI and the Leap image. Such incompatibilities can occur due to glibc version mismatches, like in #483.
=> Enable Dependabot for Dockerfile

RELEASE_NOTES.md, pkg/build/grub_test.go, pkg/build/raw_test.go, pkg/build/templates/grub/guestfish-snippet.tpl
Due to changes in the grub cmdline the sed approach no longer works, so instead we can run grub2-mkconfig via guestfish which should re-generate the grub.cfg with the defaults applied
Closes: #498
=> Fix kernelArgs issue with LeapMicro 6.0

Dockerfile
Using SLE15-SP5 with Leap 15.6 may result in dependency issues, so I added a repo to OBS which builds packages Leap-15.6
=> Dockerfile: Switch to Leap-15.6 repo

RELEASE_NOTES.md, pkg/cache/cache.go, pkg/cache/cache_test.go, pkg/combustion/combustion.go, pkg/combustion/registry.go, pkg/eib/eib.go, pkg/fileio/file_io.go, pkg/image/context.go
Closes #479 
Container images for air-gapping manifests and Helm charts are now cached to greatly decrease build times.
=> Container Image Caching

README.md
The `Prerequisites` section seems to be a leftover. These dependencies are not required on the system, since they are installed in the base Dockerfile layer.
=> Clean up building from source docs

RELEASE_NOTES.md, pkg/combustion/templates/k3s-multi-node-installer.sh.tpl, pkg/combustion/templates/k3s-single-node-installer.sh.tpl, pkg/combustion/templates/rke2-multi-node-installer.sh.tpl, pkg/combustion/templates/rke2-single-node-installer.sh.tpl
=> Rework manifest install logic

Dockerfile
Closes #367
I tested this by adding the `registry.suse.de` EIB container to the embedded artifact registry. Before making the change to the Dockerfile it would get a certificate error, after editing the Dockerfile it would work fine.
=> Add SUSE CA Certs

Dockerfile
It turns out that `golang:1.22` is a rolling release. A recent change/upgrade to this image caused our 1.0.z stream to stop building. This PR pins the go base image to a very specific version which is compatible with the rest of EIB 1.0.z.
closes: #537
=> made go base image version more explicit

pkg/image/validation/kubernetes.go, pkg/registry/registry.go
#546 upgrades to a new go base image for EIB. In doing so, the linter seems to be updated, which is causing failures. I've also seen these failures locally on a recent machine rebuild, also due to the new linter.
This fix changes the iteration to use the index to look up the objects instead of making a copy of each element during the iteration. It passes on my local linter, and if this doesn't break anything in the GitHub CI, we can land it and see if it unblocked #546.
=> corrected rangeValCopy linter error

RELEASE_NOTES.md, docs/building-images.md, pkg/combustion/combustion.go, pkg/combustion/fips.go, pkg/combustion/fips_test.go, pkg/combustion/templates/15-fips-setup.sh, pkg/eib/eib.go, pkg/image/definition.go, pkg/image/definition_test.go, pkg/image/testdata/full-valid-example.yaml, pkg/image/validation/os.go, pkg/image/validation/validation_test.go, pkg/image/validation/version.go, pkg/image/validation/version_test.go
In this PR we add support for enabling FIPS functionality with a single boolean in the image definition. In SLE Micro 5.5 it was sufficient to simply add `fips=1` to the kernel cmdline as the default image shipped with the required components, however in SL Micro 6.0 we have to perform some additional steps, at which point it's more convenient to have a single boolean. This boolean takes care of the following steps:
1. Ensures that the `patterns-base-fips` package is installed through RPM dependency resolution
2. Adds the `fips=1` kernel command line argument to the list
3. Runs the FIPS setup script at firstboot to ensure that the FIPS crypto is enabled
The resulting system has the kernel command line option, and persists reboots:
```
node1:~ # cat /proc/cmdline …
```
=> Adding support for enabling FIPS mode via an operating system boolean

README.md
> I have not verified this link yet since OBS is currently serving up 504s. This is the link mentioned in the issue which I suspect is correct, I just haven't been able to see it in action.
OBS is back up and the link pulls correctly.
closes: #570
=> updated README for current version

RELEASE_NOTES.md, pkg/rpm/resolver/templates/rpm-resolution.sh.tpl
closes: #594 
This PR offers the simplest approach in fixing the problem described in #594 by making sure that the `/tmp/rpm-repo` directory exists before executing the [zypper install](https://github.com/suse-edge/edge-image-builder/blob/main/pkg/rpm/resolver/templates/rpm-resolution.sh.tpl#L41) command.
This will ensure that we will not break the RPM resolution process if the RPM packages that have been specified for install are already present on the machine.
We might also want to think if we want a more sophisticated approach, where instead of just creating the directory beforehand we:
1. Validate the package versions that have been set for installation against the packages that have already been installed on the `base-image`
2. Only proceed to package resolution if the desired …
=> Manually create RPM cache directory

RELEASE_NOTES.md, pkg/combustion/osfiles_test.go, pkg/combustion/templates/19-copy-os-files.sh
closes: #593 
We may want to investigate a global setting of mounts, for example in the `script` file for combustion itself. Given the time constraint on 1.2, I didn't want to introduce extra risk by applying it at a global level like that. This fix solves #593 and we can address a more generalized approach when we have more time to think through the implications and properly regression test.
=> explicitly mount and unmount /var for os files handling

RELEASE_NOTES.md, pkg/combustion/templates/31-elemental-register.sh.tpl
In this PR we create the required /etc/rancher/elemental/agent directory structure during the initial Elemental setup code. A config file is checked within the systemd startup condition, and it seemingly fails if this directory isn't already in-place. This seems to only be an issue in SL Micro 6.1, but it shouldn't harm for previous versions of Micro.
Fixes #632
=> Create the required Elemental Agent directory structure during Combustion

RELEASE_NOTES.md, docs/building-images.md, pkg/combustion/registry_test.go, pkg/combustion/templates/26-embedded-registry.sh.tpl
This was a huge oversight. A solution to the RAM issue was introduced in `v1.0.2` that I completely missed. This change now allows Hauler to create the temporary directory that containers are loaded into in `/opt/hauler` as opposed to `/tmp`.
I have tested both versions of this and found that the final storage usage of `/opt/hauler` remains the same regardless of using `/tmp` or `/opt/hauler` as `--tempdir`.
=> Custom tempdir for EAR

Dockerfile, RELEASE_NOTES.md, pkg/combustion/registry_test.go, pkg/combustion/templates/26-embedded-registry.sh.tpl
Closes #638
To be merged when the new version of Hauler is available in `https://download.opensuse.org/repositories/isv:SUSE:Edge:EdgeImageBuilder/Leap-15.6/isv:SUSE:Edge:EdgeImageBuilder.repo` .
Maintains the original, low memory, Hauler usage with the new Hauler command format.
=> Update handling for Hauler v1.2.1

RELEASE_NOTES.md, pkg/combustion/combustion.go, pkg/combustion/registry.go, pkg/container/image_digester.go, pkg/container/image_digester_test.go, pkg/eib/eib.go, pkg/podman/podman.go, pkg/rpm/resolver/resolver.go
Closes #625 
For images tagged `latest`, before pulling the image we get the digest for the correct architecture and platform and append that digest to the name of the image to suit our cache implementation. This allows our caching to now properly handle images tagged `latest`. 
As a dependency to reduce the requirement for processing this programmatically, `jq` was added to the EIB container image.
=> Fix stale cache

RELEASE_NOTES.md, pkg/image/definition.go, pkg/image/definition_test.go, pkg/image/testdata/full-valid-example.yaml, pkg/image/validation/kubernetes.go, pkg/image/validation/kubernetes_test.go, pkg/registry/helm_crd.go, pkg/registry/registry.go
Closes #606 
It is a valid configuration to install multiple Helm charts to the same or different namespaces as long as the name of the release is different. In our case this would be the metadata name of the Helm charts.
This PR removes the validation that prevents defining multiple Helm charts with the same name and instead automatically appends a suffix to the metadata names to be unique.
E.g. if ‘cert-manager’ is defined twice, the metadata names in the Helm CRDs would become ‘cert-manager-1’, ‘cert-manager-2’ which deploy with no issue.
```
kube-system    job.batch/helm-install-cert-manager-1                     Complete   1/1           43s        16m
kube-system    job.batch/helm-install-cert-manager-2                     Complete   1/1           43s        16m
```
```
cert-manager …
```
=> allow duplicate helm chart names

RELEASE_NOTES.md, pkg/build/templates/rebuild-iso.sh.tpl
This was placed into release-1.1, and not main. This also needs to go into main for Edge 3.3, which leverages SL Micro 6.1, which also now has the sha256 checksums.
cherry-picks ba4e9e159989000d3cd9a8a8bc4b2761ef2030fa
=> Forward-Port: Support ISOs with SHA256 checksums (#698)

pkg/combustion/templates/19-copy-os-files.sh
Similar to https://github.com/suse-edge/edge-image-builder/issues/593, files in os-files/usr/local are not copied properly
=> explicitly mount and unmount /usr/local for os files handling
