suse-edge/edge-image-builder

- go.mod
- go.sum
- pkg/config/image.go
- pkg/config/image_test.go
- pkg/config/testdata/valid_example.yaml
This does not yet include any sort of validation on the data, that'll come in a future change.
> Added basic structure for configuration parsing

- cmd/eib/main.go
- pkg/build/build.go
- pkg/build/build_test.go
- pkg/build/message_test.go
- pkg/config/build.go
There still needs to be work done in here, but this is the basis of the new design around an image config dir instead of just a file. There are likely going to be some changes to make this run more smoothly in a container, but I'm not looking to answer that yet.
> Modifications to build from an image config dir

- pkg/build/build.go
- pkg/build/build_test.go
- pkg/build/message.go
- pkg/build/raw.go
- pkg/build/raw_test.go
- pkg/build/scripts/modify-raw-image.sh.tpl
> Refined write* methods in Builder to apply templates if specified

- pkg/build/build.go
- pkg/build/build_test.go
- pkg/build/rpm.go
- pkg/build/scripts.go
- pkg/fileio/file_io.go
- pkg/fileio/file_io_test.go
- Extracts common files writing and copying logic to a new fileio package
- Transfers and extends unit tests
- Removes unused business logic
> Bootstrap fileio package

- README.md
- docs/building-images.md
Updated for the operatingSystem section of the config file and the rpms directory support.
> Pulled out image config file/dir into their own docs

- docs/building-images.md
- pkg/combustion/templates/add-users.sh.tpl
- pkg/combustion/users_test.go
- pkg/image/definition.go
- pkg/image/definition_test.go
- pkg/image/testdata/full-valid-example.yaml
> Renamed OS user password to "encryptedPassword"

- pkg/image/definition.go
- pkg/image/testdata/full-valid-example.yaml
> added conversion to lowercase

- cmd/eib/main.go
- pkg/image/definition.go
- pkg/image/definition_test.go
- pkg/image/testdata/full-valid-example.yaml
- pkg/image/validation.go
- pkg/image/validation_test.go
This is a preliminary version of the image validation handling. There’s still much to discuss and a lot to get feedback on. Additionally, it currently fails the linter and has no tests but this will be updated soon.
> Validation

- pkg/combustion/combustion.go
- pkg/combustion/kubernetes.go
- pkg/combustion/kubernetes_test.go
- pkg/combustion/templates/15-rke2-installer.sh.tpl
- Bootstraps Kubernetes component
- Introduces single node fully airgapped RKE2 setup
- Follow ups will include:
- Revisiting kubernetes definition i.e. dropping fields such as CNI and multus which can be extracted from the config file
- HA support
- k3s support
- Documentation 😬
> Add Kubernetes component

- pkg/image/validation/image_test.go
- pkg/image/validation/os.go
- pkg/image/validation/os_test.go
- Added test for overall OS validation function
- Added component assertions for image validation
> Finished porting OS validations to the new framework

- pkg/image/definition.go
- pkg/image/definition_test.go
- pkg/image/testdata/full-valid-example.yaml
- pkg/image/validation.go
- pkg/image/validation_test.go
This PR includes the manifest definition, testing, and validation.
This will be followed up with a manifest parsing and configuration PR.
> Manifest Definition Implementation

- pkg/combustion/kubernetes.go
- pkg/combustion/kubernetes_test.go
- Drop erroring out when server config is not provided
- Establishes the following kubernetes config structure:
```
kubernetes/
├── config
├── agent.yaml # to be added later
└── server.yaml
```
> Restructure kubernetes config dir

- pkg/combustion/kubernetes.go
- pkg/combustion/kubernetes_test.go
- pkg/combustion/templates/15-k3s-single-node-installer.sh.tpl
- pkg/kubernetes/script_installer.go
- Basic skeleton of k3s implementation
- Core business logic e.g. config file handling, API VIP / API host configurations, etc. will be introduced in a follow up
> Add single node k3s

- pkg/combustion/kubernetes.go
- pkg/combustion/kubernetes_integration_test.go
- pkg/combustion/kubernetes_test.go
- pkg/combustion/templates/15-k3s-single-node-installer.sh.tpl
- pkg/combustion/templates/k8s-vip.yaml.tpl
- pkg/kubernetes/cluster.go
- pkg/kubernetes/cluster_test.go
- Add configuration file parsing + sane defaults
- Add VIP manifest parsing
> Configure single node k3s clusters

- docs/building-images.md
- pkg/cli/build/build.go
- pkg/combustion/elemental.go
- Downloads `elemental-register` and `elemental-system-agent` when the Elemental component is configured
> Download Elemental RPMs

- RELEASE_NOTES.md
- docs/building-images.md
- pkg/combustion/templates/13b-add-users.sh.tpl
- pkg/combustion/users_test.go
- pkg/image/definition.go
- pkg/image/definition_test.go
- pkg/image/testdata/full-valid-example.yaml
- pkg/template/template.go
I explicitly removed the `-m` flag from useradd; I think the default should be no user home directory. After this, I'll add a flag to user creation to allow that option to be set.
> added user group assignment

- pkg/combustion/templates/k3s-multi-node-installer.sh.tpl
- pkg/combustion/templates/k3s-single-node-installer.sh.tpl
- pkg/combustion/templates/rke2-multi-node-installer.sh.tpl
- pkg/combustion/templates/rke2-single-node-installer.sh.tpl
Change to only copy registry file if it exists.
> Manifest script change

- docs/building-images.md
> 216 - Updated systemd docs to be more accurate on its uses

- RELEASE_NOTES.md
- pkg/combustion/script.go
- pkg/combustion/script_test.go
> Added verbose output for scripts being executed

- RELEASE_NOTES.md
- pkg/combustion/network.go
- pkg/combustion/network_test.go
> Prevent network configurations for empty network directory

- pkg/combustion/rpm.go
- pkg/combustion/rpm_test.go
> 242 - Enhance rpm dir checking to look for RPMs

- pkg/combustion/templates/26-embedded-registry.sh.tpl
> Remove unnecessary indentation from embedded artifact registry template

- docs/debugging.md
Adding a stub page so I can ask the team to flesh out for their particularly areas of expertise.
> added stub for debugging page

- RELEASE_NOTES.md
- pkg/helm/helm.go
- pkg/helm/helm_test.go
- pkg/image/context.go
- pkg/registry/helm.go
- pkg/registry/helm_test.go
> Helm template namespace

- docs/design/downloads.md
Putting up a quick initial draft to get thoughts on it.
> EIB Download Design

- RELEASE_NOTES.md
- pkg/combustion/registry.go
- pkg/combustion/registry_test.go
- pkg/combustion/templates/26-embedded-registry.sh.tpl
> Embedded artifact registry memory fix

- pkg/image/validation/os.go
- pkg/image/validation/os_test.go
Minor fix to make one last validation message consistent with the rest.
> Corrected validation capitalization

- RELEASE_NOTES.md
- pkg/image/validation/os.go
- pkg/image/validation/os_test.go
> added check for ssh keys without createHomeDir

- RELEASE_NOTES.md
- pkg/image/validation/os.go
- pkg/image/validation/os_test.go
- Closes https://github.com/suse-edge/edge-image-builder/issues/384
> Improve RPM validation

- RELEASE_NOTES.md
- pkg/combustion/templates/13b-add-users.sh.tpl
- Closes https://github.com/suse-edge/edge-image-builder/issues/392
> Unmount /home after configuring users

- .github/dependabot.yaml
- Closes https://github.com/suse-edge/edge-image-builder/issues/396
> Add dependabot GH action

- examples/iso/k3s-single-node.yaml
- examples/iso/os-configuration.yaml
- examples/raw/k3s-single-node.yaml
- examples/raw/os-configuration.yaml
If these land, I'll update the docs README to mention that these exist. If we don't land these for whatever reason, it doesn't make sense to mention there since there is only a single, very basic example in here already.
> added simple examples for os and k8s

- RELEASE_NOTES.md
- pkg/build/raw_test.go
- pkg/build/templates/modify-raw-image.sh.tpl
- pkg/rpm/resolver/templates/prepare-tarball.sh.tpl
> Added support for 4096 byte sector size input base images

- RELEASE_NOTES.md
- pkg/combustion/custom.go
- pkg/combustion/custom_test.go
> [Release 1.0] Fix custom scripts permissions

- Dockerfile
- RELEASE_NOTES.md
- cmd/eib/main.go
- pkg/cli/build/version.go
- pkg/cli/cmd/version.go
- pkg/combustion/message.go
- pkg/combustion/templates/48-message.sh
- pkg/combustion/templates/48-message.sh.tpl
- pkg/version/version.go
> [Release 1.0] Version Handling

- RELEASE_NOTES.md
- pkg/build/raw_test.go
- pkg/build/templates/modify-raw-image.sh.tpl
- pkg/rpm/resolver/templates/prepare-tarball.sh.tpl
> [Release 1.0] Add support for 4096 byte sector size input base images

- RELEASE_NOTES.md
- pkg/combustion/elemental_test.go
- pkg/combustion/templates/31-elemental-register.sh.tpl
> [Release 1.0] Add Elemental Reset capabilities to nodes provisioned via EIB

- RELEASE_NOTES.md
> [Release 1.0] Update release notes for v1.0.2

- README.md
> updated README to tell users to use OBS builds

- RELEASE_NOTES.md
- pkg/helm/helm.go
- pkg/helm/helm_test.go
- pkg/image/definition.go
- pkg/image/definition_test.go
- pkg/image/testdata/full-valid-example.yaml
- pkg/registry/helm.go
- pkg/registry/helm_test.go
- pkg/registry/registry.go
- pkg/registry/registry_test.go
Closes #481 
Adds ability to specify Helm API Versions.
> Helm API Versions

- RELEASE_NOTES.md
- pkg/build/build.go
> added image name to build output

- RELEASE_NOTES.md
- pkg/kubernetes/artefact_downloader.go
- pkg/kubernetes/artefact_downloader_test.go
> arm64 RKE2 CNI download logic

- RELEASE_NOTES.md
- pkg/image/validation/kubernetes.go
- pkg/image/validation/kubernetes_test.go
> Kubernetes version validation

- RELEASE_NOTES.md
- pkg/build/iso.go
- pkg/build/templates/rebuild-iso.sh.tpl
> Adding support for kernel cmdline arguments for systems that use kexec

- RELEASE_NOTES.md
- pkg/combustion/kubernetes_test.go
- pkg/registry/helm_crd.go
> Modify Helm backOffLimit

- pkg/image/validation/validation.go
- pkg/image/validation/version.go
- pkg/image/validation/version_test.go
This is a preliminary attempt at a very simple and temporary solution to the schema validation for the new image definition version.
> Schema 1.1 Validation

- RELEASE_NOTES.md
- pkg/combustion/certificates.go
- pkg/combustion/custom.go
- pkg/combustion/kubernetes.go
- pkg/combustion/osfiles.go
- pkg/fileio/file_io.go
- pkg/fileio/file_io_test.go
- pkg/fileio/testdata/copy-files/unwritable.txt
- pkg/registry/registry.go
- pkg/rpm/resolver/resolver.go
> CopyFiles keep permissions

- RELEASE_NOTES.md
- pkg/rpm/resolver/templates/rpm-resolution.sh.tpl
See #550 for the explanation of the issue and why this approach was chosen.
closes: #550
> removed broken repo import on SLE Micro 6.0

- RELEASE_NOTES.md
- config/artifacts.yaml
- pkg/eib/eib.go
- pkg/image/context.go
- pkg/kubernetes/selinux.go
> K3s selinux rpm changes

- pkg/image/validation/kubernetes.go
Closes https://github.com/suse-edge/edge-image-builder/issues/567
> Fix validation errors propagation

- RELEASE_NOTES.md
- pkg/combustion/templates/k3s-multi-node-installer.sh.tpl
- pkg/combustion/templates/rke2-multi-node-installer.sh.tpl
> IP templating bug fix

- RELEASE_NOTES.md
- pkg/rpm/resolver/templates/rpm-resolution.sh.tpl
Closes #601 
Shoutout to @rdoxenham for the find!
> Extras Dynamic Handling

- pkg/combustion/templates/set-node-ip.sh.tpl
> Fix handling for getting default node IP

- RELEASE_NOTES.md
- docs/building-images.md
> Improve EAR docs

- RELEASE_NOTES.md
- pkg/combustion/combustion.go
- pkg/combustion/fips.go
- pkg/combustion/fips_test.go
- pkg/eib/eib.go
- pkg/image/definition.go
- pkg/image/definition_test.go
- pkg/image/validation/os.go
- pkg/image/validation/os_test.go
- pkg/image/validation/version.go
- pkg/image/validation/version_test.go
> Add FIPS Validation

- RELEASE_NOTES.md
- docs/building-images.md
- pkg/build/raw.go
- pkg/build/raw_test.go
- pkg/build/templates/modify-raw-image.sh.tpl
- pkg/eib/eib.go
- pkg/image/definition.go
- pkg/image/definition_test.go
- pkg/image/testdata/full-valid-example.yaml
- pkg/image/validation/os.go
- pkg/image/validation/os_test.go
- pkg/rpm/resolver/base.go
- pkg/rpm/resolver/templates/prepare-tarball.sh.tpl
This PR adds support for building RAW encrypted images.
> FDE handling

- RELEASE_NOTES.md
- docs/building-images.md
- pkg/image/definition_test.go
- pkg/image/testdata/full-valid-example.yaml
> EAR doc update

- RELEASE_NOTES.md
- pkg/image/validation/image.go
> Cross Arch Warning

- RELEASE_NOTES.md
- docs/building-images.md
- pkg/combustion/registry.go
- pkg/image/definition.go
- pkg/image/definition_test.go
- pkg/image/testdata/full-valid-example.yaml
- pkg/image/validation/registry.go
- pkg/image/validation/registry_test.go
> Add support for authenticated container registries

- RELEASE_NOTES.md
- docs/building-images.md
Update documentation for best practices for using `HelmChartConfigs`
> HelmChartConfigs best practices (#764)

- RELEASE_NOTES.md
- pkg/combustion/registry_test.go
- pkg/combustion/templates/26-embedded-registry.sh.tpl
> Improve Ear Service
